CREATE TABLE RecipeIngredient
(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	RecipeId INT NOT NULL FOREIGN KEY REFERENCES Recipe(RecipeId),
	IngredientId INT NOT NULL FOREIGN KEY REFERENCES Ingredient(IngredientId),
	Amount NVARCHAR(50) NOT NULL
);